# Use the official Loki image
FROM grafana/loki:latest

# Copy Loki configuration
COPY config/loki-config.yml /etc/loki/config.yml

# Define the entrypoint
CMD [ "/usr/bin/loki", "-config.file=/etc/loki/config.yml" ]
