auth_enabled: false

server:
  http_listen_port: 3100

limits_config:
  allow_structured_metadata: false  # Prevents metadata error

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb  # Use tsdb instead of boltdb-shipper
      object_store: filesystem
      schema: v13  # Upgrade to v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/working  # Ensure this line is present